---
title: "Final_Project"
author: "R.Riddell"
date: "10/10/2020"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(tidyverse)
library(janitor)
library(lubridate)
library(ggplot2)
library(plotly)
library(htmlwidgets)
library(gganimate)
library(scales)

```

```{r Cleaning Na out of dataframe}
df <- read_csv("ks-projects-201801.csv")
dim(df)

glimpse(df)

sum(is.na(df))
naniar::gg_miss_var(df)

df <-  df %>% 
  filter(complete.cases(.))

df <- clean_names(df)

df$usd_pledged <- NULL

```

Date Day, Month, Year
```{r adjusting columns and creating new variables}
# checking if date
class(df$deadline)
class(df$launched)

# changing to dat and creating day, month and year columns
df$launched <- date(df$launched)

df$deadline_year <- year(df$deadline)
df$deadline_month <- month(df$deadline, label = T)
df$deadline_day <- wday(df$deadline, label = T)

df$launched_year <- year(df$launched)
df$launched_month <- month(df$launched, label = T)
df$launched_day <- wday(df$launched, label = T)

df$campaign_length <- df$deadline - df$launched

# creating a column which is the differnce between goal and amount pledged
df$diff <- df$usd_pledged_real - df$usd_goal_real

# filetring out incorrect observations
df <- df %>% 
  filter(!launched == '1970-01-01')

```

Which main_categorties are most popular
```{r Data exploration of categories}
df %>% 
  group_by(main_category) %>% 
  count() %>% 
  ggplot(aes(main_category, n)) +
  geom_bar(stat = 'identity') +
  ggtitle('Total amount of campaigns') + 
  coord_flip()

df %>% 
  group_by(main_category) %>% 
  summarise(Total_pledged = sum(usd_pledged_real)) %>% 
  ggplot(aes(main_category, Total_pledged)) +
  geom_bar(stat = 'identity') +
  ggtitle('Total funding per category') + 
  coord_flip()

df %>% 
  group_by(main_category) %>% 
  summarise(Total_pledged = sum(usd_pledged_real),
            campaings = n(),
            pledged_per_campaign = Total_pledged/campaings) %>% 
  ggplot(aes(main_category, pledged_per_campaign)) +
  geom_bar(stat = 'identity') +
  ggtitle('average pledge per campaign') + 
  coord_flip()


```

subcategories of most common categories
```{r data exploration of subcategories}
df %>% 
  group_by(main_category) %>% 
  summarise(unique = unique(category)) %>% 
  mutate(Num_sub.cat = length(unique)) %>% 
  select(-unique) %>% 
  summarise(num = max(Num_sub.cat)) %>% 
  ggplot(aes(main_category, num)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  ggtitle('Number of sub categeories per main category') 


  
df %>% 
  filter(main_category == 'Technology') %>%
  group_by(category) %>% 
  summarise(total_pledges = sum(usd_pledged_real)) %>% 
  ggplot(aes(category, total_pledges)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  ggtitle('Technology')


df %>% 
  filter(main_category == 'Publishing') %>% 
  group_by(category) %>% 
  summarise(total_pledges = sum(usd_pledged_real)) %>% 
  ggplot(aes(category, total_pledges)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  ggtitle('Publishing')

df %>% 
  filter(main_category =='Music') %>% 
  group_by(category) %>% 
  summarise(total_pledges = sum(usd_pledged_real)) %>% 
  ggplot(aes(category, total_pledges)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  ggtitle('Music')

df %>% 
  filter(main_category =='Film & Video') %>% 
  group_by(category) %>% 
  summarise(total_pledges = sum(usd_pledged_real)) %>% 
  ggplot(aes(category, total_pledges)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  ggtitle('Film & Video')

df %>% 
  filter(main_category =='Design') %>% 
  group_by(category) %>% 
  summarise(total_pledges = sum(usd_pledged_real)) %>% 
  ggplot(aes(category, total_pledges)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  ggtitle('Design') +
  scale_y_continuous(labels = point)


ggplot(df, aes(main_category, usd_pledged_real)) +
  geom_bar(stat = 'identity') +
  scale_y_continuous(labels = format_format(big.mark = " ", decimal.mark = ",", scientific = FALSE))

point <- format_format(big.mark = " ", decimal.mark = ",", scientific = FALSE)

```

## length of campaign
```{r data exploration of campaign length}
df$campaign_length <- as.numeric(df$campaign_length)
range(df$campaign_length)

df %>%
  mutate(simple_cl = cut_interval(campaign_length, 10)) %>% 
  group_by(simple_cl) %>% 
  ggplot(aes(simple_cl, usd_pledged_real)) +
  geom_bar(stat = 'identity') +
  ggtitle('Total pledged per campaign_length')

ggplot(df,aes(campaign_length)) +
  geom_histogram() +
  ggtitle('distribution of campaign length')

ggplot(df,aes(campaign_length, usd_pledged_real)) +
  geom_bar(stat = 'identity') +
  ggtitle('Total pledged per campaign_length')

ggplot(df,aes(campaign_length, backers)) +
  geom_bar(stat = 'identity') + 
  ggtitle('number of backers per campaign_length')
```

## campaigns per country
```{r data exploration of country}
df %>% 
  group_by(country) %>% 
  count() %>% 
  ggplot(aes(country, n)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  ggtitle('number of campaigns per country')

df %>% 
  #filter(country == 'US'|
         #country == 'GB'|
         #country == 'CA'|
         #country == 'AU') %>% 
  filter(state != 'live',
         state != 'suspended') %>% 
  group_by(country, state) %>% 
  summarise(Count = n()) %>% 
  ggplot(aes(country, Count, fill = state)) +
  geom_bar(position = 'fill', stat = 'identity') +
  ggtitle('filled barplot of country success')

df %>% 
  filter(country == 'US'|
         country == 'GB'|
         country == 'CA'|
         country == 'AU') %>% 
  filter(state != 'live',
         state != 'suspended') %>% 
  group_by(country, state) %>% 
  summarise(Count = n()) %>% 
  ggplot(aes(country, Count, fill = state)) +
  geom_bar(stat = 'identity', position = 'dodge') +
  ggtitle('top 4 countries (by number of projects) success rate')

```

## pledge per backers per category
```{r data exploration of backers}
df %>% 
  summarise(average_pledge = sum(usd_pledged_real)/sum(backers))

df %>% 
  group_by(state) %>% 
  summarise(average_pledge = sum(usd_pledged_real)/sum(backers)) %>% 
  ggplot(aes(state, average_pledge)) + 
  geom_bar(stat = 'identity') +
  ggtitle('average pledge based on campaign state')

df %>% 
  group_by(main_category) %>% 
  summarise(average_pledge = sum(usd_pledged_real)/sum(backers)) %>% 
  ggplot(aes(main_category, average_pledge)) + 
  geom_bar(stat = 'identity') +
  ggtitle('average pledge based on main category') +
  coord_flip()

df %>% 
  group_by(deadline_month) %>% 
  summarise(average_pledge = sum(usd_pledged_real)/sum(backers)) %>% 
  ggplot(aes(deadline_month, average_pledge)) + 
  geom_bar(stat = 'identity') +
  ggtitle('average pledge based on deadline month') +
  coord_flip()


```

## backers vs state
```{r data exploration of backers vs state}
df %>% 
  group_by(state) %>% 
  ggplot(aes(state,backers)) +
  geom_bar(stat = 'identity') +
  ggtitle('number of backers per state')


df %>% 
  group_by(state) %>% 
  summarise(mean_backers = mean(backers)) %>% 
  ggplot(aes(state,mean_backers)) +
  geom_bar(stat = 'identity') +
  ggtitle('Average number of backers per state')


df %>% 
  group_by(main_category) %>% 
  summarise(backer_count = sum(backers)) %>% 
  ggplot(aes(main_category,backer_count)) +
  geom_bar(stat = 'identity') +
  ggtitle('total number of backers per category') +
  coord_flip()

df %>% 
  group_by(main_category) %>% 
  summarise(backer_count = mean(backers)) %>% 
  ggplot(aes(main_category,backer_count)) +
  geom_bar(stat = 'identity') +
  ggtitle('Average backers per category') +
  coord_flip()

```
## Goal amount
```{r data exploration of of Goal}

df %>% 
  group_by(deadline_month) %>% 
  summarise(mean_pledge = mean(usd_pledged_real),
            mean_goal = mean(usd_goal_real)) %>%
  ggplot(aes(deadline_month,mean_pledge, group = 2)) + 
  geom_line(aes(y=mean_pledge), color = 'blue') +
  geom_line(aes(y=mean_goal), color = 'red') +
  ggtitle('mean pledged vs mean goal')
           

df %>%
  filter(state == 'failed') %>% 
  group_by(main_category) %>% 
  summarise(dif = sum(diff)) %>% 
  ggplot(aes(main_category,dif)) + 
  geom_bar(stat = "identity") +
  coord_flip() + 
  ggtitle('Total amount fallen short per campaigns | Failed campaigns')

df %>%
  filter(state == 'failed') %>% 
  group_by(main_category) %>% 
  summarise(dif = mean(diff)) %>% 
  ggplot(aes(main_category,dif)) + 
  geom_bar(stat = "identity") +
  coord_flip() + 
  ggtitle('Mean amount fallen short per campaigns | Failed campaigns')


df %>%
  filter(state == 'successful') %>% 
  group_by(main_category) %>% 
  summarise(dif = sum(diff)) %>% 
  ggplot(aes(main_category,dif)) + 
  geom_bar(stat = "identity") +
  coord_flip() + 
  ggtitle('Total amount exceeded per campaigns | Successful campaigns')

df %>%
  filter(state == 'successful') %>% 
  group_by(main_category) %>% 
  summarise(dif = mean(diff)) %>% 
  ggplot(aes(main_category,dif)) + 
  geom_bar(stat = "identity") +
  coord_flip() + 
  ggtitle('Mean amount exceeded per campaigns | Successful campaigns')


```
## Launched exploration

```{r data exploration of launched date}
df %>% 
  group_by(launched_year) %>% 
  summarise(count = n()) %>% 
  ggplot(aes(launched_year, count, group = 1)) +
  geom_line() +
  ggtitle('projects launched per year')

df %>% 
  group_by(launched_month) %>% 
  summarise(count = n()) %>% 
  ggplot(aes(launched_month, count, group = 1)) +
  geom_line() +
  ggtitle('projects launched per month')

df %>% 
  group_by(launched_day) %>% 
  summarise(count = n()) %>% 
  ggplot(aes(launched_day, count, group = 1)) +
  geom_line() +
  ggtitle('projects launched per day')

df %>% 
  group_by(launched_year,state) %>% 
  summarise(count = n()) %>% 
  ggplot(aes(launched_year, count, color = state)) +
  geom_line() +
  ggtitle('project state breakdown per year')

df %>% 
  group_by(launched_month,state) %>% 
  summarise(count = n()) %>% 
  ggplot(aes(launched_month, count, color = state, group = state)) +
  geom_line() +
  ggtitle('project state breakdown per month')

df %>% 
  group_by(launched_day,state) %>% 
  summarise(count = n()) %>% 
  ggplot(aes(launched_day, count, color = state, group = state)) +
  geom_line() +
  ggtitle('project state breakdown per day')

```
## transformatioon of category over time
```{r animated Line graph Kickstater popularity}
df2 <- df %>% 
  group_by(launched_year, main_category) %>% 
  summarise(count = n())

ggplot(df2, aes(launched_year, count, colour = main_category, group = main_category)) +
  geom_line() +
  gganimate::transition_reveal(launched_year)
```


```{r bubble graphs with a variety of features}
df$launched_YM <- format(as.Date(df$launched),'%Y-%m')
class(df$launched_YM)
df3 <- df %>% 
  #filter(state == 'successful') %>% 
  group_by(launched_YM,main_category) %>% 
  summarise(Count = n(),
            #cs = sum(usd_pledged_real), 
            mean_pledged = mean(usd_pledged_real),
            mean_goal = mean(usd_goal_real),.groups = 'keep') 


ggplot(df3, aes(launched_year, count, fill = main_category)) +
  geom_point()

ggplot(df3, aes(x = mean_cs, y = mean_goal)) + 
  geom_point(aes(color = main_category, size = Count), alpha = 0.5) +
  #scale_color_manual(values = c("#00AFBB", "#E7B800", "#FC4E07")) +
  scale_size(range = c(0.5, 12))  # Adjust the range of points size

r1 <- plot_ly(
  df3, x = ~mean_pledged, y = ~mean_goal, frame =~launched_YM,  
  color = ~main_category, type = "scatter",
  mode="markers", size=~Count,
  marker = list(symbol = 'circle', sizemode = 'diameter',
                      line = list(width = 2, color = '#FFFFFF'), opacity=0.4)) %>% 
  animation_opts(2000,redraw = F) %>% 
  animation_slider(currentvalue = list(prefix = "Year", font = list(color = 'red')))

saveWidget(r1, file=paste0( getwd(), "/r1.html"))


df4 <- df %>% 
  #filter(state == 'successful') %>% 
  group_by(launched_YM,main_category) %>% 
  summarise(Count = n(),
            pleged = sum(usd_pledged_real),
            Goal = sum(usd_goal_real),.groups = 'keep') 

r2 <- plot_ly(
  df4, x = ~pleged, y = ~Goal, frame =~launched_YM,  
  color = ~main_category, type = "scatter",
  mode="markers", size=~Count,
  marker = list(symbol = 'circle', sizemode = 'diameter',
                      line = list(width = 2, color = '#FFFFFF'), opacity=0.4)) %>% 
  animation_opts(1000, redraw = F) %>% 
  animation_slider(currentvalue = list(prefix = "Year", font = list(color = 'red')))

saveWidget(r2, file=paste0( getwd(), "/bubble1.html"))

df %>% 
  filter(main_category == 'Food' &
           launched_year == 2014 &
           launched_month == 'Jul') 

df5 <- df %>% 
  #filter(state == 'successful') %>% 
  group_by(launched_YM,main_category) %>% 
  summarise(backers = sum(backers),
            pleged = sum(usd_pledged_real),
            Number_of_concurrent_projects = n(),.groups = 'keep') 

r3 <- plot_ly(
  df5, x = ~pleged, y = ~Number_of_concurrent_projects, frame =~launched_YM,  
  color = ~main_category, type = "scatter",
  mode="markers", size=~backers,
  marker = list(symbol = 'circle', sizemode = 'diameter',
                      line = list(width = 2, color = '#FFFFFF'), opacity=0.4)) %>% 
  animation_opts(2000, redraw = F) %>% 
  animation_slider(currentvalue = list(prefix = "Year", font = list(color = 'red')))

saveWidget(r3, file=paste0( getwd(), "/bubble2.html"))

df6 <- df %>% 
  filter(launched_year > 2013) %>% 
  group_by(launched_YM,state) %>% 
  summarise(backers = sum(backers),
            mean_pleged = mean(usd_pledged_real),
            Number_of_concurrent_projects = n(),.groups = 'keep') 

r4 <- plot_ly(
  df6, x = ~mean_pleged, y = ~Number_of_concurrent_projects, frame =~launched_YM,  
  color = ~state, type = "scatter",
  mode="markers", size=~backers,
  marker = list(symbol = 'circle', sizemode = 'diameter',
                      line = list(width = 2, color = '#FFFFFF'), opacity=0.4)) %>% 
  animation_opts(500, redraw = F, mode = 'next') %>% 
  animation_slider(currentvalue = list(prefix = "Year", font = list(color = 'red')))

saveWidget(r4, file=paste0( getwd(), "/bubble4.html"))


```


```{r animted line graphs}
df7 <- df %>% 
  filter(state != 'live') %>% 
  group_by(state,launched_YM) %>% 
  summarise(count = n(),.groups = 'keep') %>% ungroup()

lineG <- ggplot(df7, aes(launched_YM, count, colour = state, group = state)) +
  geom_line(size = 2) +
  theme_bw() +
  transition_reveal(launched_YM, keep_last = T) + 
  view_follow() +
  ease_aes('back-in') 

animate(lineG, duration = 15, fps = 60, renderer = gifski_renderer(loop = FALSE), height = 800, width = 1600) 
anim_save <- lineG + exit_shrink()
anim_save('Line_graph.gif', animtion = anim_save)

?exit_shrink()

anim_save(lineG)
?ease_aes
accumulate_by <- function(dat, var) {
  var <- lazyeval::f_eval(var, dat)
  lvls <- plotly:::getLevels(var)
  dats <- lapply(seq_along(lvls), function(x) {
    cbind(dat[var %in% lvls[seq(1, x)], ], frame = lvls[[x]])
  })
  bind_rows(dats)
}

min_date <- min(df$launched)
min_date <- ymd_hms("2009-04-21 00:00:00")
min_Date_ms <- interval("1970-01-01 00:00:00", min_date) / dmilliseconds(1)

max_date <- max(df$launched)
max_date <- ymd_hms("2018-01-02 00:00:00")
max_Date_ms <- interval("1970-01-01 00:00:00", max_date) / dmilliseconds(1)


df$launched_YM <- parse_date(df$launched_YM, format = '%Y-%m')
class(df$launched_YM)          

fig <- df7 

fig <- fig %>%  accumulate_by(~launched_YM)

fig <- fig %>%
  plot_ly(
    x = ~launched_YM, 
    y = ~count,
    split = ~state,
    frame = ~frame,
    type = 'scatter',
    mode = 'lines+markers',
    line = list(simplyfy = F)) %>% 
  layout(xaxis = list(range = c(min_Date_ms,max_Date_ms)))
  #animation_opts(frame = 2000, redraw = F) %>% 
  #animation_slider(hide = T) %>% 
  #animation_button(x = 1, xanchor = "right", y = 0, yanchor = "bottom")

saveWidget(fig, file=paste0( getwd(), "/line.html"))

range(df7$launched_YM)
```

```{r decsion tree modelling to understand variable importance}
library(caret)
control_obj <- trainControl(
  method = "cv",
  number = 10,
  savePredictions = "final",
  classProbs = T 
)

set.seed(345)

tree_mdl  <- train(state ~. , data = df_c ,
                   method = 'rpart',
                   tuneGrid = expand.grid(cp = seq(0.01,0.1,0.01)),
                   trControl = control_obj,
                   metric = "ROC")

tree_mdl
plot(tree_mdl)
rattle::fancyRpartPlot(tree_mdl$finalModel, sub = "", palettes = 'RdBu')
plot(varImp(tree_mdl), top =20)

glimpse(df_c)

df_c <- df

df_c <- df_c %>% 
  slice(1:50000)

df_c <- df_c  %>% 
  select(-c(diff, name, id, pledged,usd_pledged_real))


df_c <- df_c  %>% 
  filter(state == 'successful'|
           state == 'failed')

df_c <- df_c %>% 
  mutate_at(vars(category,main_category,currency,country,state), as.factor)

df_c$state <- factor(df_c$state)

levels(droplevels(df_c$state))

unique(df_c$state)
```

```{r Shiny app showing category and success or failure}

sdf <- df %>% 
  group_by(main_category,state) %>% 
  filter(state != 'live', state != 'suspended') %>% 
  count()
  

library(shiny)

ui <- fluidPage(
  #numericInput(inputId = "n",
               #"sample size", value = 25),
      selectInput("mySelectInput", 
                  'Select from the dropdown:',
                  choices = unique(sdf$main_category)),
  plotOutput(outputId = "scatter"),
  textOutput("niceSelectOutput"))

server <- function(input,output){
  
  xvalues <- reactive({sdf %>% filter(main_category == input$mySelectInput) %>% ungroup() %>%  select(state)})
  yvalues <- reactive({sdf %>% filter(main_category == input$mySelectInput) %>% ungroup() %>%  select(n)})
  
  output$scatter <- renderPlot({
    ggplot(data = NULL,aes(unlist(xvalues()),unlist(yvalues()))) + geom_bar(stat = 'identity') +
      xlab(input$mySelectInput) +
      ggtitle("Distribution of Iris data") +
      theme_bw()})

}

shinyApp(ui = ui, server = server)

x <- sdf %>% filter(main_category == 'Art') %>% ungroup() %>%  select(state)
y <- sdf %>% filter(main_category == 'Art') %>% ungroup() %>%  select(n)

ggplot(sdf,aes(unlist(x),unlist(y))) + geom_bar(stat = 'identity')



```

```{r Visualisations for presentation}
# what is the relationship between goal and categories
df_goal <- df %>%
  filter(!state == 'live', !state == 'suspended', !state == 'canceled') %>% 
  group_by(main_category) %>% 
  summarise(mean_goal = mean(usd_goal_real),
            mean_pledge = mean(usd_pledged_real),
            diff = mean(diff),
            diff = abs(diff),
            success = sum(state == 'successful')/ (sum(state == 'successful')+sum(state == 'failed')))

df_showPLot <- df_goal[df_goal$main_category == 'Technology'|
                        df_goal$main_category == 'Journalism'|
                        df_goal$main_category == 'Food'|
                        df_goal$main_category == 'Design'|
                        df_goal$main_category == 'Games'|
                        df_goal$main_category == 'Dance'|
                        df_goal$main_category == 'Comics'|
                        df_goal$main_category == 'Theater'|
                        df_goal$main_category == 'Music',]

t <- list(family = 'sans serif', size = 10, color = toRGB('grey50'))

a <- list(
  x = df_goal$mean_goal  ,
  y = df_goal$mean_pledge,
  text = df_goal$main_category,
  xref = "x",
  yref = "y",
  showarrow = T,
  arrowhead = 2,
  ax = 20,
  ay = -40
)


goal_pledge_diff <- plot_ly(
  df_goal, x = ~mean_goal, y = ~mean_pledge,
  color = ~main_category, type = "scatter", #text = ~main_category, textposition = "left", textfont = t,
  mode="markers", size=~success,
  marker = list(symbol = 'circle', sizemode = 'diameter',
                      line = list(width = 2), opacity=0.4, showlegend = T)) %>%
  layout(legend = list(x = 0.1, y = 0.9),
         title = "Mean Pledge vs Mean Goal",
         xaxis = list(title = 'Mean Goal USD'),
         yaxis = list(title = 'Mean Pledge USD'),
         annotations = a)


saveWidget(goal_pledge_diff, file=paste0( getwd(), "/goalBubble.html"))

#exceeded vs fell shorts
df_pos <- df %>%
  filter(!state == 'live', !state == 'suspended', !state == 'canceled') %>% 
  filter(diff > 0) %>% 
  group_by(main_category) %>% 
  summarise(Mean_pos = mean(diff)) 
            
df_neg <- df %>%
  filter(!state == 'live', !state == 'suspended', !state == 'canceled') %>% 
  filter(diff < 0) %>% 
  group_by(main_category) %>% 
  summarise(Mean_neg = mean(diff))             
            
df_pos_neg <- left_join(df_pos, df_neg)

df_pos_neg %>%
  pivot_longer(cols = c(Mean_pos,Mean_neg)) %>% 
  mutate(bad = if_else(main_category == 'Theater'|main_category == 'Dance','Bad','fine')) %>% 
  ggplot(aes(main_category,value, fill = name, alpha = main_category)) + 
  geom_bar(stat = "identity", position = 'stack') +
  coord_flip() + 
  scale_alpha_manual(values = c(.2,.2,.2,.2,1,.2,.2,.2,1,.2,.2,.2,.2,1,.2)) +
  guides(alpha = F) +
  ggtitle('Mean amount failed or succeded') +
  ylab('Amount (thousands)') + 
  xlab('Category') +
  scale_y_continuous(labels = label_number(scale = 1e-3, big.mark = ",")) + 
  scale_fill_discrete(labels = c('Failed', 'Successful')) +
  labs(fill = 'Project State')

df_pos_neg %>%
  pivot_longer(cols = c(Mean_pos,Mean_neg)) %>% 
  mutate(bad = if_else(main_category == 'Theater'|main_category == 'Dance','Bad','fine')) %>% 
  ggplot(aes(main_category,value, fill = name, alpha = main_category)) + 
  geom_bar(stat = "identity", position = 'stack') +
  coord_flip() + 
  scale_alpha_manual(values = c(1,.2,.2,.2,.2,.2,1,.2,.2,1,.2,.2,.2,.2,1)) +
  guides(alpha = F) +
  ggtitle('Mean amount failed or succeded') +
  ylab('Amount (thousands)') + 
  xlab('Category') +
  scale_y_continuous(labels = label_number(scale = 1e-3, big.mark = ",")) + 
  scale_fill_discrete(labels = c('Failed', 'Successful')) +
  labs(fill = 'Project State')

# what is the relationship between goal and launch month
df %>% 
  filter(!state == 'live', !state == 'suspended', !state == 'canceled') %>% 
  group_by(launched_month, state) %>% 
  summarise(Median = median(usd_goal_real)) %>% 
  ggplot(aes(launched_month, Median, group = state, fill = state, alpha = launched_month)) +
  geom_bar(stat = 'identity', position = 'stack') +
  scale_alpha_manual(values = c(.5,.5,.5,1,1,1,.5,.5,1,1,1,.5)) +
  guides(alpha = F)+
  theme_bw() +
  ggtitle('Median Goal per Launch Month') +
  ylab('Amount ($)') + 
  xlab('Launch Month') +
  scale_fill_discrete(labels = c('Failed','Successful')) +
  labs(fill = 'Project State')

# what is the relationship between goal and campaign length 
df$campaign_length <- as.numeric(df$campaign_length)

df$campaign_length_simple <- cut_interval(df$campaign_length,10)
unique(df$campaign_length_simple)

Line_Goal <- df %>% 
  filter(!state == 'live', !state == 'suspended', !state == 'canceled') %>% 
  group_by(campaign_length_simple) %>% 
  summarise('Total Goal' = sum(usd_goal_real),
            'Total Pledged' = sum(usd_pledged_real)) %>% 
  pivot_longer(cols = c('Total Goal','Total Pledged')) %>%
  mutate(row_number = row_number()) %>% 
  ggplot(aes(campaign_length_simple, value, group = name, color = name)) +
  geom_line(size = 2) + 
  ggtitle('Total Goal and Total Pledged') +
  xlab('Campaign Length') +
  ylab('Total Goal of Project (000,000)') +
  theme_bw()+
  theme(plot.title = element_text(size = 30, face = 'bold', hjust = 0.5),
        axis.title.x = element_text(size = 20, hjust = 0.5),
        axis.title.y = element_text(size = 20, hjust = 0.5),
        legend.position = 'right',
        axis.text.x = element_text(angle = 45, vjust = 1, size = 15, hjust = 1),
        axis.text.y = element_text(angle = 45, size = 15),
        legend.title = element_blank(),
        legend.text = element_text(size = 20)) +
  scale_y_continuous(labels = label_number(scale = 1e-6, big.mark = ",")) +
  scale_x_discrete(labels = c('1 to 10 days',
                              '11 to 18 days',
                              '19 to 27 days',
                              '28 to 36 days',
                              '37 to 45 days',
                              '46 to 54 days',
                              '55 to 63 days',
                              '64 to 72 days',
                              '73 to 81 days',
                              '82 to 92 days')) + 
   transition_reveal(row_number, keep_last = T)


animate(Line_Goal, duration = 5, fps = 60, renderer = gifski_renderer(loop = FALSE), height = 800, width = 1600) 
anim_save <- Line_Goal + exit_shrink()
anim_save('Line_graph_goal.gif', animtion = anim_save)

df %>% 
  filter(!state == 'live', !state == 'suspended', !state == 'canceled') %>% 
  group_by(state) %>% 
  summarise(mean= mean(usd_goal_real)) %>% 
  mutate(mean = round(mean, digits = 0)) %>% 
  ggplot(aes(state, mean, fill = state)) +
  geom_bar(stat = 'identity') +
  geom_text(aes(label=mean), vjust=1.6, color="white",position = position_dodge(0.9), size=4)+
  ggtitle('Mean Goal') +
  ylab('Amount') + 
  xlab('Project State') +
  scale_fill_discrete(labels = c('Successful','Failed')) +
  scale_x_discrete(labels = c('Failed', 'Successful'))+
  theme(plot.title = element_text(size = 12, face = 'bold', hjust = 0.5),
        axis.title.x = element_text(size = 10, hjust = 0.5),
        axis.title.y = element_text(size = 10, hjust = 0.5),
        legend.position = 'none',
        axis.text.x = element_text(angle = 0, size = 8),
        axis.text.y = element_text(angle = 0, size = 8))
```

```{r meeting critera or not meeting criteria}
df %>% 
  filter(campaign_length > 19 & campaign_length < 45) %>% 
  filter(launched_month == 'Apr'| launched_month == 'May'| launched_month == 'Jun'| 
           launched_month == 'Sep'| launched_month == 'Oct'| launched_month == 'Nov') %>% 
  filter(main_category == 'Games'| main_category == 'Design'|
         main_category == 'Comics'| main_category == 'Dance'| main_category == 'Music') %>% 
  filter(!state == 'live', !state == 'suspended', !state == 'canceled') %>% 
  group_by(state) %>% 
  summarise(count = n(),
            mean_pledge = mean(usd_pledged_real)) %>% 
  pivot_longer(c('count', 'mean_pledge')) %>% 
  ggplot(aes(name, value, fill = state)) + 
  geom_bar(stat = 'identity', position = 'dodge') +
  theme_bw() +
  ggtitle('Projects that are suitable to Kickstater') +
  ylab(' ') + 
  xlab(' ') +
  scale_fill_discrete(labels = c('Failed','Successful')) +
  labs(fill = 'Project State') +
  scale_x_discrete(labels =c('Number of Projects', 'Mean Pledge USD'))




df %>% 
  filter(campaign_length < 19 | campaign_length > 45) %>% 
  filter(!launched_month == 'Apr'| !launched_month == 'May'| !launched_month == 'Jun'| 
           !launched_month == 'Sep'| !launched_month == 'Oct'| !launched_month == 'Nov') %>% 
  filter(!main_category == 'Games'| !main_category == 'Design'|
         !main_category == 'Comics'| !main_category == 'Dance'| !main_category == 'Music') %>% 
  filter(!state == 'live', !state == 'suspended', !state == 'canceled') %>% 
  group_by(state) %>% 
  summarise(count = n(),
            mean_pledge = mean(usd_pledged_real)) %>% 
  pivot_longer(c('count', 'mean_pledge')) %>% 
  ggplot(aes(name, value, fill = state)) + 
  geom_bar(stat = 'identity', position = 'dodge') +
  theme_bw() +
  ggtitle('Projects that may not be suitable to Kickstater') +
  ylab(' ') + 
  xlab(' ') +
  scale_fill_discrete(labels = c('Failed','Successful')) +
  labs(fill = 'Project State') +
  scale_x_discrete(labels =c('Number of Projects', 'Mean Pledge USD')) 


```

```{r}
df %>% 
  filter(!state == 'live', !state == 'suspended', !state == 'canceled') %>% 
  group_by(state) %>% 
  count() %>% 
  mutate(frame = if_else(state == 'failed', 'a', 'b')) %>% 
  ggplot(aes(state, n, fill = state)) +
  geom_bar(stat = 'identity') +
  geom_text(aes(label=n), vjust=1.6, color="white",position = position_dodge(0.9), size=4)+
  ggtitle('Total Projects') +
  ylab('Amount') + 
  xlab('Project State') +
  scale_fill_discrete(labels = c('Successful','Failed')) +
  scale_x_discrete(labels = c('Failed', 'Successful'))+
  theme(plot.title = element_text(size = 12, face = 'bold', hjust = 0.5),
        axis.title.x = element_text(size = 10, hjust = 0.5),
        axis.title.y = element_text(size = 10, hjust = 0.5),
        legend.position = 'none',
        axis.text.x = element_text(angle = 0, size = 8),
        axis.text.y = element_text(angle = 0, size = 8)) 


```






















